(SERVER-262) Fix `puppetserver gem env` subcommand
Without this patch the `puppetserver gem env` subcommand bombs out with
the following error:

    ERROR:  While executing gem ... (NoMethodError)
        undefined method `split' for nil:NilClass

The problem is a result of clearing the entire system environment
resulting in `ENV['PATH']` being `nil`.  This patch addresses the
problem by associating GEM_HOME and other variables into the system
environment rather than clearing it.

Conflicts:
	src/clj/puppetlabs/puppetserver/cli/gem.clj

Conflict resolved by removing Wayne's JARS_NO_REQUIRE change.